"""Read access to uploaded objects. Keys are generated by the web app; only that exact shape is accepted."""

from __future__ import annotations

import re
from pathlib import Path
from typing import TYPE_CHECKING, Protocol

if TYPE_CHECKING:
    from cca.settings import Settings

_UUID = r"[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}"
_KEY_RE = re.compile(rf"^uploads/{_UUID}/{_UUID}$")


class InvalidStorageKeyError(ValueError):
    pass


class ObjectTooLargeError(ValueError):
    pass


class ObjectMissingError(LookupError):
    pass


def assert_valid_key(key: str) -> None:
    if not _KEY_RE.match(key):
        raise InvalidStorageKeyError("invalid storage key")


class ObjectStore(Protocol):
    def read(self, key: str, max_bytes: int) -> bytes: ...

    def delete(self, key: str) -> None:
        """Remove the object. Deleting a missing object is not an error (idempotent)."""
        ...


def key_belongs_to_tenant(key: str, tenant_id: str) -> bool:
    return bool(_KEY_RE.match(key)) and key.startswith(f"uploads/{tenant_id}/")


class LocalObjectStore:
    def __init__(self, root: Path) -> None:
        self._root = root.resolve()

    def path_for(self, key: str) -> Path:
        assert_valid_key(key)
        full = self._root.joinpath(*key.split("/")).resolve()
        if not full.is_relative_to(self._root) or full == self._root:
            raise InvalidStorageKeyError("invalid storage key")
        return full

    def read(self, key: str, max_bytes: int) -> bytes:
        path = self.path_for(key)
        try:
            size = path.stat().st_size
        except FileNotFoundError as exc:
            raise ObjectMissingError(key) from exc
        if size > max_bytes:
            raise ObjectTooLargeError(key)
        return path.read_bytes()

    def delete(self, key: str) -> None:
        self.path_for(key).unlink(missing_ok=True)


class R2ObjectStore:
    """Cloudflare R2 via the S3 API. Credentials are R2 tokens, never AWS credentials."""

    def __init__(self, account_id: str, access_key_id: str, secret_access_key: str, bucket: str) -> None:
        import boto3  # imported lazily so local runs need no S3 client

        self._bucket = bucket
        self._client = boto3.client(
            "s3",
            endpoint_url=f"https://{account_id}.r2.cloudflarestorage.com",
            aws_access_key_id=access_key_id,
            aws_secret_access_key=secret_access_key,
            region_name="auto",
        )

    def read(self, key: str, max_bytes: int) -> bytes:
        assert_valid_key(key)
        try:
            head = self._client.head_object(Bucket=self._bucket, Key=key)
        except self._client.exceptions.ClientError as exc:
            raise ObjectMissingError(key) from exc
        if head["ContentLength"] > max_bytes:
            raise ObjectTooLargeError(key)
        body = self._client.get_object(Bucket=self._bucket, Key=key)["Body"].read(max_bytes + 1)
        if len(body) > max_bytes:
            raise ObjectTooLargeError(key)
        return bytes(body)

    def delete(self, key: str) -> None:
        assert_valid_key(key)
        self._client.delete_object(Bucket=self._bucket, Key=key)  # S3 semantics: missing is fine


def object_store(settings: Settings) -> ObjectStore:
    if settings.storage_driver == "r2":
        return R2ObjectStore(
            settings.r2_account_id or "",
            settings.r2_access_key_id or "",
            settings.r2_secret_access_key or "",
            settings.r2_bucket or "",
        )
    assert settings.local_storage_dir is not None
    return LocalObjectStore(settings.local_storage_dir)
